/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.client.gui;

import rs.ac.bg.fon.nprog.domen.Korisnik;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.nprog.client.kontoler.Kontroler;

/**
 *
 * @author tamara
 */
public class FrmPrijava extends javax.swing.JFrame {
    private final int MAX_BROJ_POKUSAJA=3;
    private int brojPokusaja=0;
    /**
     * Creates new form FrmPrijava
     */
    public FrmPrijava() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        pnPrijava = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblLozinka = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();
        btnPrijava = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOpcije = new javax.swing.JMenu();
        lblRegistracija = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrijava.setBackground(new java.awt.Color(153, 153, 153));
        pnPrijava.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prijava", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pnPrijava.setForeground(new java.awt.Color(102, 102, 102));

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email: ");

        lblLozinka.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblLozinka.setForeground(new java.awt.Color(255, 255, 255));
        lblLozinka.setText("Lozinka:");

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        txtLozinka.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        btnPrijava.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPrijava.setForeground(new java.awt.Color(102, 102, 102));
        btnPrijava.setText("Prijava");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/nprog/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnPrijavaLayout = new javax.swing.GroupLayout(pnPrijava);
        pnPrijava.setLayout(pnPrijavaLayout);
        pnPrijavaLayout.setHorizontalGroup(
            pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrijavaLayout.createSequentialGroup()
                .addGroup(pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrijavaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnPrijavaLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnPrijavaLayout.setVerticalGroup(
            pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrijavaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrijavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLozinka)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jmOpcije.setForeground(new java.awt.Color(102, 102, 102));
        jmOpcije.setText("Opcije");
        jmOpcije.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        lblRegistracija.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRegistracija.setText("Registracija");
        lblRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRegistracijaActionPerformed(evt);
            }
        });
        jmOpcije.add(lblRegistracija);

        jMenuBar1.add(jmOpcije);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        // TODO add your handling code here:
        if(brojPokusaja<MAX_BROJ_POKUSAJA){
            String email=txtEmail.getText().trim();
            String lozinka=txtLozinka.getText();
            String lozinkaHash=Kontroler.vratiInstancu().MD5Hash(lozinka);
            Korisnik korisnik=new Korisnik(-1,null,null,null,email,lozinkaHash);
            try {
                Korisnik ulogovan = Kontroler.vratiInstancu().ulogujKorisnika(korisnik);
                //JOptionPane.showMessageDialog(this, "Uspesno logovanje");
                new FrmMain(ulogovan).setVisible(true);
                this.dispose();
                
                
            } catch (Exception ex) {
            	JOptionPane.showMessageDialog(this, ex.getMessage());
                int preostalo;
                brojPokusaja++;
                preostalo=MAX_BROJ_POKUSAJA-brojPokusaja;
                if(brojPokusaja==MAX_BROJ_POKUSAJA){
                    JOptionPane.showMessageDialog(this, "Nemate vise pokušaja");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Preostalo pokušaja: "+preostalo);
//                    JOptionPane.showMessageDialog(this, "Sistem ne može da izvrši prijavu korisnika.");
                    
                }
                
                //JOptionPane.showMessageDialog(this,ex.getMessage(),"Greška, preostalo:"+brojPokusaja+" pokušaja.", JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(FrmPrijavaPronalaska.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnPrijavaActionPerformed

    private void lblRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRegistracijaActionPerformed
        // TODO add your handling code here:
        new FrmRegistracija(this,true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistracijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JMenu jmOpcije;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLozinka;
    private javax.swing.JMenuItem lblRegistracija;
    private javax.swing.JPanel pnPrijava;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtLozinka;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        this.setTitle("Prijava korisnika");
    }
}
