/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.client.gui;

import rs.ac.bg.fon.nprog.domen.Pronalazak;
import java.util.Date;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.nprog.client.kontoler.Kontroler;
import rs.ac.bg.fon.nprog.client.modeli.ModelTabelePronalazak;

/**
 *
 * @author tamara
 */
public class FrmPretragaPronalazaka extends javax.swing.JFrame {
    
    /**
     * Creates new form frmPretragaPronalazaka
     */
    public FrmPretragaPronalazaka() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPretragaPronalazaka = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPronalazak = new javax.swing.JTable();
        txtDatumResavanjaSlucaja = new javax.swing.JTextField();
        lblDatumResavanjaSlucaja = new javax.swing.JLabel();
        btnDetaljiPronalaska = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnPretraga = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        lblErrorDatum = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pretraga pronalazaka");

        pnPretragaPronalazaka.setBackground(new java.awt.Color(153, 153, 153));
        pnPretragaPronalazaka.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pronalasci", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pnPretragaPronalazaka.setToolTipText("");

        tblPronalazak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPronalazak);

        txtDatumResavanjaSlucaja.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtDatumResavanjaSlucaja.setForeground(new java.awt.Color(102, 102, 102));
        txtDatumResavanjaSlucaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumResavanjaSlucajaActionPerformed(evt);
            }
        });

        lblDatumResavanjaSlucaja.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblDatumResavanjaSlucaja.setForeground(new java.awt.Color(255, 255, 255));
        lblDatumResavanjaSlucaja.setText("Datum rešavanja slučaja:");

        btnDetaljiPronalaska.setBackground(new java.awt.Color(204, 204, 204));
        btnDetaljiPronalaska.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnDetaljiPronalaska.setForeground(new java.awt.Color(102, 102, 102));
        btnDetaljiPronalaska.setText("Detalji");
        btnDetaljiPronalaska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiPronalaskaActionPerformed(evt);
            }
        });

        btnNazad.setBackground(new java.awt.Color(204, 204, 204));
        btnNazad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(102, 102, 102));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnPretraga.setBackground(new java.awt.Color(204, 204, 204));
        btnPretraga.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPretraga.setForeground(new java.awt.Color(102, 102, 102));
        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnPonisti.setBackground(new java.awt.Color(204, 204, 204));
        btnPonisti.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPonisti.setForeground(new java.awt.Color(102, 102, 102));
        btnPonisti.setText("Poništi");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        lblErrorDatum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblErrorDatum.setForeground(new java.awt.Color(255, 0, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/nprog/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnPretragaPronalazakaLayout = new javax.swing.GroupLayout(pnPretragaPronalazaka);
        pnPretragaPronalazaka.setLayout(pnPretragaPronalazakaLayout);
        pnPretragaPronalazakaLayout.setHorizontalGroup(
            pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPretragaPronalazakaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addComponent(btnDetaljiPronalaska, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnPretragaPronalazakaLayout.createSequentialGroup()
                                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDatumResavanjaSlucaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPonisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txtDatumResavanjaSlucaja)))
                            .addComponent(lblErrorDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnPretragaPronalazakaLayout.setVerticalGroup(
            pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPretragaPronalazakaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumResavanjaSlucaja)
                    .addComponent(txtDatumResavanjaSlucaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPretragaPronalazakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetaljiPronalaska, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPretragaPronalazaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPretragaPronalazaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatumResavanjaSlucajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumResavanjaSlucajaActionPerformed
         pretraga();
    }//GEN-LAST:event_txtDatumResavanjaSlucajaActionPerformed

    private void btnDetaljiPronalaskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiPronalaskaActionPerformed
        // TODO add your handling code here:
        int index=tblPronalazak.getSelectedRow();
        if(index>=0){ 
            ModelTabelePronalazak mtp=(ModelTabelePronalazak) tblPronalazak.getModel();
            Pronalazak pronalazak;
            try {
                pronalazak = Kontroler.vratiInstancu().ucitajPronalazak(mtp.getLista().get(index));
                new FrmPronalazak(this, true, EnumModForme.SHOW, pronalazak, this).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }else{
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita pronalazak. ", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnDetaljiPronalaskaActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        // TODO add your handling code here:
        pretraga();
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        try {
            // TODO add your handling code here:
            ModelTabelePronalazak mtp=(ModelTabelePronalazak) tblPronalazak.getModel();
            mtp.osvezi(Kontroler.vratiInstancu().nadjiPronalaske(new Pronalazak()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPonistiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljiPronalaska;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumResavanjaSlucaja;
    private javax.swing.JLabel lblErrorDatum;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnPretragaPronalazaka;
    private javax.swing.JTable tblPronalazak;
    private javax.swing.JTextField txtDatumResavanjaSlucaja;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        this.setTitle("Pretraga pronalazaka");
        lblErrorDatum.setVisible(false);
        tblPronalazak.setModel(new ModelTabelePronalazak(new ArrayList<Pronalazak>()));
        popuniTabelu();
    }

    private void popuniTabelu() {
        
        List<Pronalazak> listaPronalazaka;
        try {
            Pronalazak pronalazak=new Pronalazak();
            listaPronalazaka = Kontroler.vratiInstancu().nadjiPronalaske(pronalazak);
            ModelTabelePronalazak mtp=new ModelTabelePronalazak(listaPronalazaka);
            tblPronalazak.setModel(mtp);
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public void pretraga(){
        Pronalazak pronalazak=new Pronalazak();
        ModelTabelePronalazak mtp=(ModelTabelePronalazak) tblPronalazak.getModel();
        Date datumResavanjaSlucaja;
        try {
            datumResavanjaSlucaja=Kontroler.vratiInstancu().parseDatum(txtDatumResavanjaSlucaja.getText().trim());
        } catch (ParseException ex) {
            //JOptionPane.showMessageDialog(this, "Format datuma koji je prihvatljiv je dd-MM-yyyy");
            lblErrorDatum.setVisible(true);
            lblErrorDatum.setText("Format datuma koji je prihvatljiv je dd-MM-yyyy");
            //Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe pronalaske po zadatoj vrednosti", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        lblErrorDatum.setVisible(false);
        pronalazak.setDatumResavanjaSlucaja(datumResavanjaSlucaja);
        List<Pronalazak> listaPronalaska;
        try {
            listaPronalaska = Kontroler.vratiInstancu().nadjiPronalaske(pronalazak);
            mtp.osvezi(listaPronalaska);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    void osveziListu() {
        ModelTabelePronalazak mtp=(ModelTabelePronalazak) tblPronalazak.getModel();
        try {
            mtp.osvezi(Kontroler.vratiInstancu().nadjiPronalaske(new Pronalazak()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaPronalazaka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
