/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.client.gui;

import rs.ac.bg.fon.nprog.domen.EnumPol;
import rs.ac.bg.fon.nprog.domen.Korisnik;
import rs.ac.bg.fon.nprog.domen.Lokacija;
import rs.ac.bg.fon.nprog.domen.PrijavaPronalaskaPsa;
import rs.ac.bg.fon.nprog.domen.Rasa;
import rs.ac.bg.fon.nprog.domen.ZahtevZaTrazenjePsa;
import rs.ac.bg.fon.nprog.client.helper.MapHelper;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.nprog.client.kontoler.Kontroler;

/**
 *
 * @author tamara
 */
public class FrmZahtevZaTrazenje extends javax.swing.JDialog {
    EnumModForme mod;
    ZahtevZaTrazenjePsa zahtevZaTrazenjePsa;
    Korisnik ulogovan;
    FrmMain glavnaForma;
    BufferedImage bi;
    private double x=0;
    private double y=0;
    private final double xBeograd=44.81691551782855;
    private final double yBeograd=20.3961181640625;
    /**
     * Creates new form frmZahtevZaTrazenje
     */
    public FrmZahtevZaTrazenje(java.awt.Frame parent, boolean modal, EnumModForme mod, ZahtevZaTrazenjePsa zahtevZaTrazenjePsa, FrmMain glavnaForma, Korisnik ulogovan ) {
        super(parent, modal);
        initComponents();
        txtSlika.setEnabled(false);
        txtSlika.setEditable(false);
        this.glavnaForma=glavnaForma;
        this.ulogovan=ulogovan;
        this.zahtevZaTrazenjePsa=zahtevZaTrazenjePsa;   
        srediFormu();
        this.mod=mod;
        primeniMod(mod);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnZahtevZaTrazenjePsa = new javax.swing.JPanel();
        lblZahtevZaTrazenjePsaId = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        lblRasa = new javax.swing.JLabel();
        lblStarost = new javax.swing.JLabel();
        lblBoja = new javax.swing.JLabel();
        lblLokacija = new javax.swing.JLabel();
        lblPol = new javax.swing.JLabel();
        lblVremeNestanka = new javax.swing.JLabel();
        lblSlika = new javax.swing.JLabel();
        lblKontaktVlasnika = new javax.swing.JLabel();
        txtZahtevZaTrazenjePsaId = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtKontaktVlasnika = new javax.swing.JTextField();
        cbRasa = new javax.swing.JComboBox<>();
        cbPol = new javax.swing.JComboBox<>();
        cbLokacija = new javax.swing.JComboBox<>();
        txtVremeNestanka = new javax.swing.JTextField();
        txtSlika = new javax.swing.JTextField();
        txtStarost = new javax.swing.JTextField();
        txtBoja = new javax.swing.JTextField();
        btnIzmeniZahtev = new javax.swing.JButton();
        btnObrisiZahtev = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnSacuvajZahtev = new javax.swing.JButton();
        lblErrorVremeNestanka = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblPrikazSlike = new javax.swing.JLabel();
        btnIzaberi = new javax.swing.JButton();
        btnDodajLokaciju = new javax.swing.JButton();
        btnPrikaziMapu = new javax.swing.JButton();
        txtOpis = new javax.swing.JTextField();
        lblOpis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zahtev za traženje psa");

        pnZahtevZaTrazenjePsa.setBackground(new java.awt.Color(153, 153, 153));
        pnZahtevZaTrazenjePsa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podaci o psu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblZahtevZaTrazenjePsaId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblZahtevZaTrazenjePsaId.setForeground(new java.awt.Color(255, 255, 255));
        lblZahtevZaTrazenjePsaId.setText("ID");

        lblIme.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblIme.setForeground(new java.awt.Color(255, 255, 255));
        lblIme.setText("Ime");

        lblRasa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRasa.setForeground(new java.awt.Color(255, 255, 255));
        lblRasa.setText("Rasa");

        lblStarost.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStarost.setForeground(new java.awt.Color(255, 255, 255));
        lblStarost.setText("Starost");

        lblBoja.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBoja.setForeground(new java.awt.Color(255, 255, 255));
        lblBoja.setText("Boja");

        lblLokacija.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblLokacija.setForeground(new java.awt.Color(255, 255, 255));
        lblLokacija.setText("Lokacija");

        lblPol.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPol.setForeground(new java.awt.Color(255, 255, 255));
        lblPol.setText("Pol");

        lblVremeNestanka.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblVremeNestanka.setForeground(new java.awt.Color(255, 255, 255));
        lblVremeNestanka.setText("Vreme nestanka");

        lblSlika.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSlika.setForeground(new java.awt.Color(255, 255, 255));
        lblSlika.setText("Slika");

        lblKontaktVlasnika.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblKontaktVlasnika.setForeground(new java.awt.Color(255, 255, 255));
        lblKontaktVlasnika.setText("Kontakt vlasnika");

        txtZahtevZaTrazenjePsaId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtZahtevZaTrazenjePsaId.setForeground(new java.awt.Color(102, 102, 102));

        txtIme.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtIme.setForeground(new java.awt.Color(102, 102, 102));

        txtKontaktVlasnika.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtKontaktVlasnika.setForeground(new java.awt.Color(102, 102, 102));

        cbRasa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbRasa.setForeground(new java.awt.Color(102, 102, 102));
//        cbRasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPol.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbPol.setForeground(new java.awt.Color(102, 102, 102));
//        cbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbLokacija.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbLokacija.setForeground(new java.awt.Color(102, 102, 102));
//        cbLokacija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLokacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLokacijaActionPerformed(evt);
            }
        });

        txtVremeNestanka.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtVremeNestanka.setForeground(new java.awt.Color(102, 102, 102));

        txtSlika.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtSlika.setForeground(new java.awt.Color(102, 102, 102));

        txtStarost.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtStarost.setForeground(new java.awt.Color(102, 102, 102));

        txtBoja.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtBoja.setForeground(new java.awt.Color(102, 102, 102));

        btnIzmeniZahtev.setBackground(new java.awt.Color(204, 204, 204));
        btnIzmeniZahtev.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnIzmeniZahtev.setForeground(new java.awt.Color(102, 102, 102));
        btnIzmeniZahtev.setText("Izmeni");
        btnIzmeniZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZahtevActionPerformed(evt);
            }
        });

        btnObrisiZahtev.setBackground(new java.awt.Color(204, 204, 204));
        btnObrisiZahtev.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnObrisiZahtev.setForeground(new java.awt.Color(102, 102, 102));
        btnObrisiZahtev.setText("Obriši");
        btnObrisiZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZahtevActionPerformed(evt);
            }
        });

        btnNazad.setBackground(new java.awt.Color(204, 204, 204));
        btnNazad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(102, 102, 102));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnSacuvajZahtev.setBackground(new java.awt.Color(204, 204, 204));
        btnSacuvajZahtev.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnSacuvajZahtev.setForeground(new java.awt.Color(102, 102, 102));
        btnSacuvajZahtev.setText("Sačuvaj");
        btnSacuvajZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajZahtevActionPerformed(evt);
            }
        });

        lblErrorVremeNestanka.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblErrorVremeNestanka.setForeground(new java.awt.Color(255, 0, 0));

        lblError.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/nprog/img/logo.png"))); // NOI18N

        btnIzaberi.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnIzaberi.setForeground(new java.awt.Color(102, 102, 102));
        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        btnDodajLokaciju.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnDodajLokaciju.setForeground(new java.awt.Color(102, 102, 102));
        btnDodajLokaciju.setText("Dodaj");
        btnDodajLokaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajLokacijuActionPerformed(evt);
            }
        });

        btnPrikaziMapu.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPrikaziMapu.setForeground(new java.awt.Color(102, 102, 102));
        btnPrikaziMapu.setText("Prikaži");
        btnPrikaziMapu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziMapuActionPerformed(evt);
            }
        });

        txtOpis.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        lblOpis.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblOpis.setForeground(new java.awt.Color(255, 255, 255));
        lblOpis.setText("Opis lokacije");

        javax.swing.GroupLayout pnZahtevZaTrazenjePsaLayout = new javax.swing.GroupLayout(pnZahtevZaTrazenjePsa);
        pnZahtevZaTrazenjePsa.setLayout(pnZahtevZaTrazenjePsaLayout);
        pnZahtevZaTrazenjePsaLayout.setHorizontalGroup(
            pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                        .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorVremeNestanka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblZahtevZaTrazenjePsaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStarost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblKontaktVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVremeNestanka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLokacija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOpis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajLokaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(btnPrikaziMapu))
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnObrisiZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzmeniZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacuvajZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblPrikazSlike, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKontaktVlasnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVremeNestanka, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtZahtevZaTrazenjePsaId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbRasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStarost)
                                    .addComponent(txtBoja)
                                    .addComponent(cbPol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnIzaberi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSlika, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20))
        );
        pnZahtevZaTrazenjePsaLayout.setVerticalGroup(
            pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addComponent(lblZahtevZaTrazenjePsaId)
                                .addGap(18, 18, 18)
                                .addComponent(lblIme)
                                .addGap(142, 142, 142)
                                .addComponent(lblPol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLokacija))
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lblRasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStarost)
                                .addGap(18, 18, 18)
                                .addComponent(lblBoja)))
                        .addGap(45, 45, 45)
                        .addComponent(lblOpis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVremeNestanka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKontaktVlasnika)
                        .addGap(18, 18, 18)
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorVremeNestanka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlika))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(cbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                                .addComponent(txtZahtevZaTrazenjePsaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStarost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodajLokaciju)
                            .addComponent(btnPrikaziMapu))
                        .addGap(7, 7, 7)
                        .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVremeNestanka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKontaktVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSlika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnZahtevZaTrazenjePsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addComponent(btnObrisiZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeniZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSacuvajZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnZahtevZaTrazenjePsaLayout.createSequentialGroup()
                        .addComponent(lblPrikazSlike, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnZahtevZaTrazenjePsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnZahtevZaTrazenjePsa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void cbLokacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLokacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLokacijaActionPerformed

    private void btnIzmeniZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZahtevActionPerformed
        // TODO add your handling code here:
       mod=EnumModForme.EDIT;
       primeniMod(mod);
    }//GEN-LAST:event_btnIzmeniZahtevActionPerformed

    private void btnObrisiZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZahtevActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            if(txtZahtevZaTrazenjePsaId.getText().isEmpty()){
                throw new Exception();
            }
            long id=Integer.parseInt(txtZahtevZaTrazenjePsaId.getText());
//            File file = new File(zahtevZaTrazenjePsa.getSlikaURL().getDescription()); 
//            file.delete();
            ZahtevZaTrazenjePsa zahtevZaTrazenjePsa=new ZahtevZaTrazenjePsa();
            zahtevZaTrazenjePsa.setZahtevZaTrazenjePsaId(id);
            zahtevZaTrazenjePsa.setSlikaURL(new ImageIcon(txtSlika.getText()));
            Kontroler.vratiInstancu().obrisiZahtevZaTrazenjePsa(zahtevZaTrazenjePsa);
            //JOptionPane.showMessageDialog(this, "Sistem je obrisao prijavu pronalaska psa.");
            glavnaForma.osveziListe();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPrijavaPronalaska.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiZahtevActionPerformed

    private void btnSacuvajZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajZahtevActionPerformed
        // TODO add your handling code here:
        
            Rasa r=(Rasa) cbRasa.getSelectedItem();
            Lokacija l=(Lokacija) cbLokacija.getSelectedItem();
            EnumPol pol=EnumPol.valueOf(cbPol.getSelectedItem().toString());
            String boja=txtBoja.getText();

            String ime=txtIme.getText();
            String kontaktVlasnika=txtKontaktVlasnika.getText();
            
            String opis=txtOpis.getText();
            
            String uvezenaSlika=txtSlika.getText();
            if(uvezenaSlika.isEmpty()){
                lblError.setVisible(true);
                lblError.setText("Molimo vas popunite sva polja");
                return;
            }
            String konacnaPutanja=dajPutanju(uvezenaSlika);
            
            if(boja.isEmpty() || uvezenaSlika.isEmpty() || ime.isEmpty() || kontaktVlasnika.isEmpty() ||txtStarost.getText().isEmpty() || opis.isEmpty()){
                lblError.setVisible(true);
                lblError.setText("Molimo vas popunite sva polja");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti zahtev za traženje psa.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(x==0 && y==0){
                lblError.setText("Molimo vas izaberite lokaciju sa mape.");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti zahtev za traženje psa.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            lblError.setVisible(false);
            int starost=Integer.parseInt(txtStarost.getText());
            Date vremeNestanka;
            try {
                vremeNestanka=Kontroler.vratiInstancu().parseDatumVreme(txtVremeNestanka.getText());
            } catch (ParseException ex) {
                lblErrorVremeNestanka.setVisible(true);
                lblErrorVremeNestanka.setText("Prihvatljiv format za datum je dd-MM-yyyy hh:mm");
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti zahtev za traženje psa.", "Greška", JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(FrmPrijavaPronalaska.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
             lblErrorVremeNestanka.setVisible(false);
            long id;
            if(mod==EnumModForme.EDIT){
                id=Integer.parseInt(txtZahtevZaTrazenjePsaId.getText());
            }else{
                id=-1;
            }
        try {
            ImageIcon slika;
            if(zahtevZaTrazenjePsa!=null && zahtevZaTrazenjePsa.getSlikaURL().getDescription().equals(txtSlika.getText())){
                slika=zahtevZaTrazenjePsa.getSlikaURL();
                ZahtevZaTrazenjePsa zahtevZaTrazenjePsa=new ZahtevZaTrazenjePsa(id, pol, boja, vremeNestanka, kontaktVlasnika, slika, starost, ime, r, l,x, y, opis, ulogovan);
                Kontroler.vratiInstancu().zapamtiZahtevZaTrazenjePsa(zahtevZaTrazenjePsa);
                //primeniMod(EnumModForme.SHOW);
                glavnaForma.osveziListe();
                this.dispose();
                
            }else{
                //slika=sacuvajSliku(konacnaPutanja);
                slika = new ImageIcon(txtSlika.getText());
                if(slika==null){
                    System.out.println("Slika je null");
                    return;
                }
                ZahtevZaTrazenjePsa zahtevZaTrazenjePsa=new ZahtevZaTrazenjePsa(id, pol, boja, vremeNestanka, kontaktVlasnika, slika, starost, ime, r, l,x,y, opis, ulogovan);
                Kontroler.vratiInstancu().zapamtiZahtevZaTrazenjePsa(zahtevZaTrazenjePsa);
                primeniMod(EnumModForme.SHOW);
                glavnaForma.osveziListe();
                this.dispose();
            }
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmZahtevZaTrazenje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajZahtevActionPerformed

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(null);
        File f = jfc.getSelectedFile();
        if(f==null){
            return;
        }
        String path=f.getAbsolutePath();
        lblPrikazSlike.setIcon(null);
        Kontroler.vratiInstancu().ucitajSliku(path, lblPrikazSlike);
        try {
            //System.out.println(path);
            bi = ImageIO.read(f);
            
        } catch (IOException ex) {
            Logger.getLogger(FrmPrijavaPronalaska.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSlika.setText(path);
    }//GEN-LAST:event_btnIzaberiActionPerformed

    private void btnPrikaziMapuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziMapuActionPerformed
        // TODO add your handling code here:
        MapHelper mapa=new MapHelper();
        if(zahtevZaTrazenjePsa!=null){
            mapa.prikaziNaMapi(zahtevZaTrazenjePsa.getX(), zahtevZaTrazenjePsa.getY());
        }
        
    }//GEN-LAST:event_btnPrikaziMapuActionPerformed

    private void btnDodajLokacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajLokacijuActionPerformed
        // TODO add your handling code here:MapHelper mapHelper=new MapHelper();
        MapHelper mapHelper=new MapHelper();
        mapHelper.setFormaZahteva(this);
        System.out.println("Pocetna vrednost: "+mapHelper.getLokacijaReturn());
        if(zahtevZaTrazenjePsa!=null){
            //ako postoji zahtev prikazi tamo gde je njegova lokacija
            mapHelper.mapaZahtev(zahtevZaTrazenjePsa.getX(),zahtevZaTrazenjePsa.getY());
        }else{
            //ako je mode=new onda neka default bude beograd
            mapHelper.mapaZahtev(xBeograd, yBeograd);
        }
        
        
    }//GEN-LAST:event_btnDodajLokacijuActionPerformed

    private void srediFormu() {
        //lblErrorVremeNestanka.setVisible(false);
        //lblError.setVisible(false);
        popuniComboLokacija();
        popuniComboRasa();
        popuniComboPol();
        popuniVrednosti();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajLokaciju;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzmeniZahtev;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiZahtev;
    private javax.swing.JButton btnPrikaziMapu;
    private javax.swing.JButton btnSacuvajZahtev;
    private javax.swing.JComboBox<Object> cbLokacija;
    private javax.swing.JComboBox<String> cbPol;
    private javax.swing.JComboBox<Object> cbRasa;
    private javax.swing.JLabel lblBoja;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblErrorVremeNestanka;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKontaktVlasnika;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLokacija;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblPrikazSlike;
    private javax.swing.JLabel lblRasa;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblStarost;
    private javax.swing.JLabel lblVremeNestanka;
    private javax.swing.JLabel lblZahtevZaTrazenjePsaId;
    private javax.swing.JPanel pnZahtevZaTrazenjePsa;
    private javax.swing.JTextField txtBoja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKontaktVlasnika;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtSlika;
    private javax.swing.JTextField txtStarost;
    private javax.swing.JTextField txtVremeNestanka;
    private javax.swing.JTextField txtZahtevZaTrazenjePsaId;
    // End of variables declaration//GEN-END:variables

    private void primeniMod(EnumModForme mod) {
       switch(mod){
           case EDIT:
               txtOpis.setEnabled(false);
               btnDodajLokaciju.setEnabled(true);
               btnDodajLokaciju.setVisible(true);
               
               btnPrikaziMapu.setVisible(false);
               btnPrikaziMapu.setEnabled(false);
               
               
               txtIme.setEnabled(true);
               txtBoja.setEnabled(true);
               txtKontaktVlasnika.setEnabled(true);
               txtSlika.setEnabled(true);
               txtVremeNestanka.setEnabled(true);
               txtStarost.setEnabled(true);
               
               //lblZahtevZaTrazenjePsaId.setVisible(true);
               //txtZahtevZaTrazenjePsaId.setVisible(true);
               txtZahtevZaTrazenjePsaId.setEnabled(false);
             
               btnIzaberi.setEnabled(true);
               
               cbLokacija.setEnabled(true);
               cbRasa.setEnabled(true);
               cbPol.setEnabled(true);
               
               btnIzmeniZahtev.setVisible(false);
               btnNazad.setVisible(true);
               btnSacuvajZahtev.setVisible(true);
               btnObrisiZahtev.setVisible(false);
               break;
           case SHOW:
               txtOpis.setEnabled(false);
               btnDodajLokaciju.setEnabled(false);
               btnDodajLokaciju.setVisible(false);
               
               btnPrikaziMapu.setVisible(true);
               btnPrikaziMapu.setEnabled(true);
               
               txtIme.setEnabled(false);
               txtBoja.setEnabled(false);
               txtKontaktVlasnika.setEnabled(false);
               txtSlika.setEnabled(false);
               txtVremeNestanka.setEnabled(false);
               txtStarost.setEnabled(false);
               
               //lblZahtevZaTrazenjePsaId.setVisible(true);
               //txtZahtevZaTrazenjePsaId.setVisible(true);
               txtZahtevZaTrazenjePsaId.setEnabled(false);
             
               btnIzaberi.setEnabled(false);
               
               cbLokacija.setEnabled(false);
               cbRasa.setEnabled(false);
               cbPol.setEnabled(false);
               
               btnIzmeniZahtev.setVisible(true);
               btnNazad.setVisible(true);
               btnSacuvajZahtev.setVisible(false);
               btnObrisiZahtev.setVisible(true);
               break;
           case NEW: 
               txtOpis.setEnabled(false);
               btnDodajLokaciju.setEnabled(true);
               btnDodajLokaciju.setVisible(true);
               
               btnPrikaziMapu.setVisible(false);
               btnPrikaziMapu.setEnabled(false);
               
               
               txtIme.setEnabled(true);
               txtBoja.setEnabled(true);
               txtKontaktVlasnika.setEnabled(true);
               txtSlika.setEnabled(true);
               txtVremeNestanka.setEnabled(true);
               txtStarost.setEnabled(true);
               
               
               
               btnIzaberi.setEnabled(true);
               //lblZahtevZaTrazenjePsaId.setVisible(false);
               //txtZahtevZaTrazenjePsaId.setVisible(false);
               txtZahtevZaTrazenjePsaId.setEnabled(false);
              
               
               cbLokacija.setEnabled(true);
               cbRasa.setEnabled(true);
               cbPol.setEnabled(true);
               
               btnIzmeniZahtev.setVisible(false);
               btnNazad.setVisible(true);
               btnSacuvajZahtev.setVisible(true);
               btnObrisiZahtev.setVisible(false);
               break;
       }
    }

    private void popuniVrednosti() {
        if(zahtevZaTrazenjePsa!=null){
            txtZahtevZaTrazenjePsaId.setText(zahtevZaTrazenjePsa.getZahtevZaTrazenjePsaId()+"");
            txtIme.setText(zahtevZaTrazenjePsa.getIme());
            cbRasa.setSelectedItem(zahtevZaTrazenjePsa.getRasa());
            txtStarost.setText(zahtevZaTrazenjePsa.getStarost()+"");
            txtBoja.setText(zahtevZaTrazenjePsa.getBoja());
            cbPol.setSelectedItem(EnumPol.valueOf(zahtevZaTrazenjePsa.getPol().toString()));
            cbLokacija.setSelectedItem(zahtevZaTrazenjePsa.getLokacija());
            txtVremeNestanka.setText(Kontroler.vratiInstancu().formatDatumVreme(zahtevZaTrazenjePsa.getVremeNestanka()));
            txtSlika.setText(zahtevZaTrazenjePsa.getSlikaURL().getDescription());
            Kontroler.vratiInstancu().ucitajSliku(zahtevZaTrazenjePsa.getSlikaURL().getDescription(),lblPrikazSlike);
            txtKontaktVlasnika.setText(zahtevZaTrazenjePsa.getKontaktVlasnika());
            txtOpis.setText(zahtevZaTrazenjePsa.getOpis());
        }
    }

    public void popuniComboLokacija() {
         try {
            List<Lokacija> listaLokacija=Kontroler.vratiInstancu().ucitajListuLokacija();
            cbLokacija.removeAllItems();
            for(Lokacija l:listaLokacija){
                cbLokacija.addItem(l);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmZahtevZaTrazenje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniComboRasa() {
         try {
            List<Rasa> listaRasa=Kontroler.vratiInstancu().ucitajListuRasa();
            cbRasa.removeAllItems();
            for(Rasa r:listaRasa){
                cbRasa.addItem(r);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmZahtevZaTrazenje.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void popuniComboPol() {
        cbPol.removeAllItems();
        for(EnumPol pol:EnumPol.values()){
            cbPol.addItem(pol.toString());
        }
    }
     private ImageIcon sacuvajSliku(String path) throws Exception{
        try {

            ImageIO.write(bi, "jpg", new File (path));
            ImageIcon slika=new ImageIcon(path);
            return slika;
        } catch (IOException ex) {
            Logger.getLogger(FrmPrijavaPronalaska.class.getName()).log(Level.SEVERE, null, ex);
            throw new Exception();
        }
    }

    private String dajPutanju(String path) {
            int indeksZagrade=path.lastIndexOf("/");
            String ime=path.substring(indeksZagrade+1,path.length()-4);
            Timestamp tmp=new Timestamp(new Date().getTime());
            String putanja="/Users/tamara/NetBeansProjects/IzgubljeniNadjeniPsi_server/images/zahtevi/"+ime+"_"+tmp+".jpg";
            //String putanja="/Users/tamara/NetBeansProjects/IzgubljeniNadjeniPsi_server/images/zahtevi/"+tmp+".jpg";
            //ImageIO.write(bi, "jpg", new File (putanja));
            return putanja;
    }

    public void promeniPolje(String opis, double x, double y) {
        //cbLokacija.setSelectedItem(sacuvana);
        txtOpis.setText(opis);
        this.x=x;
        this.y=y;
    }
}
